# Generated by Django 6.0.4 on 2026-04-27 10:38

import django.utils.timezone
from datetime import timedelta
from django.db import migrations, models


def _default_expiry():
    return django.utils.timezone.now() + timedelta(hours=24)


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='idempotencykey',
            name='request_hash',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idempotencykey',
            name='expires_at',
            field=models.DateTimeField(default=_default_expiry),
        ),
        migrations.AddIndex(
            model_name='idempotencykey',
            index=models.Index(fields=['expires_at'], name='payouts_ide_expires_abc123_idx'),
        ),
        migrations.AlterField(
            model_name='idempotencykey',
            name='key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='idempotencykey',
            unique_together={('key', 'merchant')},
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['merchant', 'type'], name='payouts_led_merchan_1baf67_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['merchant', 'status'], name='payouts_pay_merchan_9a626f_idx'),
        ),
    ]
